const ACTION_TYPES={
    LOGOUT:"LOGOUT",
    LOGIN_SUCCESS:"SUCCESS_LOGIN",
    LOGIN_FAILURE:"FAILURE",
    SIGN_UP_SUCCESS:"SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE:"SIGN_UP_FAILURE"
}
export default ACTION_TYPES